### ISSUE TITLE
Addition of arbitrary metadata to POST uploads

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom-data-generator#1]
It's be useful to allow metadata to be delivered along with the log data.  Obvious candidates are System and Environment, although others such as FQDN are used in other log types, so it's probably best to allow any metadata names somehow.  Probably sufficient to have a single value for each type per instance, so if we wanted both Ref and Prod environments, we'd just run two instances of the generator.

**Comment by gcdev373** [comment]
This can already be achieved (in effect).
All the headers end up in the `.meta` file, which can be generated via a template.  So if you want additional headers, just change the template.

This simple [example ](https://github.com/gchq/stroom-data-generator/blob/master/templates/reference/users/meta) sets the EffectiveDate, as required for reference data, but any other keys can also be created via additional lines in the template.
